version: '3'
services:
  backend:
    build: back-end/
    ports:
      - 3001:3001
    # parâmetros
    # ...
  frontend:
   build: front-end/
   ports:
      - 3000:3000
    # ...
    # parâmetros
    # ...
  # ...