version: '3'
services:
  todoback:
   build: ./todo-app/back-end
   ports:
      - 3001:3001
  todofront:
   build: ./todo-app/front-end
   depends_on:
    - todoback
   ports:
      - 3000:3000
   environment:
    - REACT_APP_API_HOST=localhost
  todotests:
   build: ./todo-app/tests
   depends_on:
      - todofront
      - todoback
   environment:
      - FRONT_HOST=todofront